### ISSUE TITLE
Sublime Package Control Error

### ISSUE THREAD

**Issue by heyycap** [nojanath/SublimeKSP#137]
When I open Sublime Text (unregistered, v3.0, build 3143), I get this error in the console:

Package Control: Error downloading package. HTTP exception InvalidCertificateException (Host codeload.github.com returned an invalid certificate ([SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:548))) downloading https://codeload.github.com/nojanath/SublimeKSP/zip/1.8.4.
error: Package Control

Unable to download KSP (Kontakt Script Processor). Please view the console for more details.

Any ideas on what went wrong and how to fix it? If I go to the url for the zip manually, it downloads without a problem.

Thanks.

**Comment by pryzmusic** [comment]
At this point, I am assuming this is resolved. Usually, these errors are fixed by just trying again or at a different time, as in rare occasions, internet downloads can break at random.

**Comment by heyycap** [comment]
No, I still get this error. What I discovered was that this kept getting added to the user preferences:

```
"ignored_packages":
	[
		"KSP (Kontakt Script Processor)",
		"Vintage"
	],
```

I'm not sure what Vintage is, but by removing "KSP (Kontakt Script Processor)", and saving, KSP then works and I can switch the language at the bottom left to KSP and work on scripts and compile them as usual.

After I quit, however, the next time I open Sublime Text, I will get the same error and KSP will have been re-added to the list of ignored packages.
