### ISSUE TITLE
"pers" keyword doesn't compile if variable name starts with a number

### ISSUE THREAD

**Issue by mkruselj** [nojanath/SublimeKSP#83]
```
on init
	declare pers 1st
end on
```

Doesn't work.

```
on init
	declare 1st
  	make_persistent(1st)
end on
```

Works (of course).

**Comment by mkruselj** [comment]
Fixed by tweaking preprocessor_plugins.py, line 31. Changed from:

```
variableNameRe = r'(?P<whole>(?P<prefix>\b|[?~$%!@])(?P<name>[a-zA-Z_][a-zA-Z0-9_\.]*))\b' # A variable name
```

to:

```
variableNameRe = r'(?P<whole>(?P<prefix>\b|[?~$%!@])(?P<name>[a-zA-Z0-9_][a-zA-Z0-9_\.]*))\b' # A variable name
```

**Comment by neblix** [comment]
You forgot to also adjust variableNameUnRe.  I got it. Thanks!

**Comment by mkruselj** [comment]
That one doesn't seem to be used at all in HandlePersistence function (which is where the bug happens)... but it might pop up somewhere else, yeah...

**Comment by neblix** [comment]
Fixed in commit  ef2e7

**Comment by Levitanus** [comment]
KSP understands variables being started with digits? )
Thanks

**Comment by mkruselj** [comment]
Yes!
